# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/temp/gopro-lib-imu-analysis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/temp/gopro-lib-imu-analysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/temp/gopro-lib-imu-analysis/CMakeFiles /home/ubuntu/temp/gopro-lib-imu-analysis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/temp/gopro-lib-imu-analysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IMUAnalysis

# Build rule for target.
IMUAnalysis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IMUAnalysis
.PHONY : IMUAnalysis

# fast build rule for target.
IMUAnalysis/fast:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/build
.PHONY : IMUAnalysis/fast

#=============================================================================
# Target rules for targets named IMUAnalysisShared

# Build rule for target.
IMUAnalysisShared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IMUAnalysisShared
.PHONY : IMUAnalysisShared

# fast build rule for target.
IMUAnalysisShared/fast:
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/build
.PHONY : IMUAnalysisShared/fast

# Manual pre-install relink rule for target.
IMUAnalysisShared/preinstall:
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/preinstall
.PHONY : IMUAnalysisShared/preinstall

#=============================================================================
# Target rules for targets named gpmf_parser

# Build rule for target.
gpmf_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpmf_parser
.PHONY : gpmf_parser

# fast build rule for target.
gpmf_parser/fast:
	$(MAKE) -f gpmf/CMakeFiles/gpmf_parser.dir/build.make gpmf/CMakeFiles/gpmf_parser.dir/build
.PHONY : gpmf_parser/fast

src/generic.o: src/generic.cpp.o
.PHONY : src/generic.o

# target to build an object file
src/generic.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/generic.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/generic.cpp.o
.PHONY : src/generic.cpp.o

src/generic.i: src/generic.cpp.i
.PHONY : src/generic.i

# target to preprocess a source file
src/generic.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/generic.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/generic.cpp.i
.PHONY : src/generic.cpp.i

src/generic.s: src/generic.cpp.s
.PHONY : src/generic.s

# target to generate assembly for a file
src/generic.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/generic.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/generic.cpp.s
.PHONY : src/generic.cpp.s

src/gp5imu_Madgwick.o: src/gp5imu_Madgwick.cpp.o
.PHONY : src/gp5imu_Madgwick.o

# target to build an object file
src/gp5imu_Madgwick.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/gp5imu_Madgwick.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/gp5imu_Madgwick.cpp.o
.PHONY : src/gp5imu_Madgwick.cpp.o

src/gp5imu_Madgwick.i: src/gp5imu_Madgwick.cpp.i
.PHONY : src/gp5imu_Madgwick.i

# target to preprocess a source file
src/gp5imu_Madgwick.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/gp5imu_Madgwick.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/gp5imu_Madgwick.cpp.i
.PHONY : src/gp5imu_Madgwick.cpp.i

src/gp5imu_Madgwick.s: src/gp5imu_Madgwick.cpp.s
.PHONY : src/gp5imu_Madgwick.s

# target to generate assembly for a file
src/gp5imu_Madgwick.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/gp5imu_Madgwick.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/gp5imu_Madgwick.cpp.s
.PHONY : src/gp5imu_Madgwick.cpp.s

src/mountainbiking.o: src/mountainbiking.cpp.o
.PHONY : src/mountainbiking.o

# target to build an object file
src/mountainbiking.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/mountainbiking.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/mountainbiking.cpp.o
.PHONY : src/mountainbiking.cpp.o

src/mountainbiking.i: src/mountainbiking.cpp.i
.PHONY : src/mountainbiking.i

# target to preprocess a source file
src/mountainbiking.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/mountainbiking.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/mountainbiking.cpp.i
.PHONY : src/mountainbiking.cpp.i

src/mountainbiking.s: src/mountainbiking.cpp.s
.PHONY : src/mountainbiking.s

# target to generate assembly for a file
src/mountainbiking.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/mountainbiking.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/mountainbiking.cpp.s
.PHONY : src/mountainbiking.cpp.s

src/skateboarding.o: src/skateboarding.cpp.o
.PHONY : src/skateboarding.o

# target to build an object file
src/skateboarding.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/skateboarding.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/skateboarding.cpp.o
.PHONY : src/skateboarding.cpp.o

src/skateboarding.i: src/skateboarding.cpp.i
.PHONY : src/skateboarding.i

# target to preprocess a source file
src/skateboarding.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/skateboarding.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/skateboarding.cpp.i
.PHONY : src/skateboarding.cpp.i

src/skateboarding.s: src/skateboarding.cpp.s
.PHONY : src/skateboarding.s

# target to generate assembly for a file
src/skateboarding.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/skateboarding.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/skateboarding.cpp.s
.PHONY : src/skateboarding.cpp.s

src/snowboarding.o: src/snowboarding.cpp.o
.PHONY : src/snowboarding.o

# target to build an object file
src/snowboarding.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/snowboarding.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/snowboarding.cpp.o
.PHONY : src/snowboarding.cpp.o

src/snowboarding.i: src/snowboarding.cpp.i
.PHONY : src/snowboarding.i

# target to preprocess a source file
src/snowboarding.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/snowboarding.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/snowboarding.cpp.i
.PHONY : src/snowboarding.cpp.i

src/snowboarding.s: src/snowboarding.cpp.s
.PHONY : src/snowboarding.s

# target to generate assembly for a file
src/snowboarding.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/snowboarding.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/snowboarding.cpp.s
.PHONY : src/snowboarding.cpp.s

src/surfing.o: src/surfing.cpp.o
.PHONY : src/surfing.o

# target to build an object file
src/surfing.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/surfing.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/surfing.cpp.o
.PHONY : src/surfing.cpp.o

src/surfing.i: src/surfing.cpp.i
.PHONY : src/surfing.i

# target to preprocess a source file
src/surfing.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/surfing.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/surfing.cpp.i
.PHONY : src/surfing.cpp.i

src/surfing.s: src/surfing.cpp.s
.PHONY : src/surfing.s

# target to generate assembly for a file
src/surfing.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/surfing.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/surfing.cpp.s
.PHONY : src/surfing.cpp.s

src/tools.o: src/tools.cpp.o
.PHONY : src/tools.o

# target to build an object file
src/tools.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/tools.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/tools.cpp.o
.PHONY : src/tools.cpp.o

src/tools.i: src/tools.cpp.i
.PHONY : src/tools.i

# target to preprocess a source file
src/tools.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/tools.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/tools.cpp.i
.PHONY : src/tools.cpp.i

src/tools.s: src/tools.cpp.s
.PHONY : src/tools.s

# target to generate assembly for a file
src/tools.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/tools.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/tools.cpp.s
.PHONY : src/tools.cpp.s

src/types.o: src/types.cpp.o
.PHONY : src/types.o

# target to build an object file
src/types.cpp.o:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/types.cpp.o
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/types.cpp.o
.PHONY : src/types.cpp.o

src/types.i: src/types.cpp.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.cpp.i:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/types.cpp.i
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/types.cpp.i
.PHONY : src/types.cpp.i

src/types.s: src/types.cpp.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.cpp.s:
	$(MAKE) -f CMakeFiles/IMUAnalysis.dir/build.make CMakeFiles/IMUAnalysis.dir/src/types.cpp.s
	$(MAKE) -f CMakeFiles/IMUAnalysisShared.dir/build.make CMakeFiles/IMUAnalysisShared.dir/src/types.cpp.s
.PHONY : src/types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... IMUAnalysis"
	@echo "... IMUAnalysisShared"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gpmf_parser"
	@echo "... src/generic.o"
	@echo "... src/generic.i"
	@echo "... src/generic.s"
	@echo "... src/gp5imu_Madgwick.o"
	@echo "... src/gp5imu_Madgwick.i"
	@echo "... src/gp5imu_Madgwick.s"
	@echo "... src/mountainbiking.o"
	@echo "... src/mountainbiking.i"
	@echo "... src/mountainbiking.s"
	@echo "... src/skateboarding.o"
	@echo "... src/skateboarding.i"
	@echo "... src/skateboarding.s"
	@echo "... src/snowboarding.o"
	@echo "... src/snowboarding.i"
	@echo "... src/snowboarding.s"
	@echo "... src/surfing.o"
	@echo "... src/surfing.i"
	@echo "... src/surfing.s"
	@echo "... src/tools.o"
	@echo "... src/tools.i"
	@echo "... src/tools.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

